# Differentiable projections to polytopes

In this notebook we explor projections of a vector into the exterior of a polytope. The polytope can be defined as $$

In [1]:
import torchsort
import torch

import numpy as np 
import pandas as pd

# Projection to Permutahedron

$$
u = (n, n-1, \dots, 1, 0) \in \mathbb{R}^{n+1}, \qquad 
\mathrm{Perm}(u) := \operatorname{conv}\{\;\sigma(u) : \sigma \in S_{n+1}\;\}.
$$

**soft rank https://arxiv.org/abs/2002.08871

### Hard projection

In [16]:
x = torch.tensor([[8, -1, 5, 3, 2, 1, 6, 7, 9, 100]]) 

torchsort.soft_rank(x)

tensor([[ 8.,  1.,  5.,  4.,  3.,  2.,  6.,  7.,  9., 10.]])

### soft projection

In [18]:
x = torch.tensor([[8, -1, 5, 3, 2, 1, 6, 7, 9, 100]]) 

torchsort.soft_rank(x, regularization_strength=2)

tensor([[ 6.7778,  2.2778,  5.2778,  4.2778,  3.7778,  3.2778,  5.7778,  6.2778,
          7.2778, 10.0000]])

# Projection to hypercube

In [23]:
def proportion_of_ones(tensor):
    return torch.sum(tensor == 1).item() / torch.numel(tensor)

def get_hypercube_tensor(n,p):
    # Ensure p is between 0 and 1
    assert 0 <= p <= 1, "p must be between 0 and 1"
    # Calculate the number of 1's
    num_ones = int(n * p)
    # Create a tensor with n zeros
    tensor = torch.zeros(n)
    # Set the first num_ones elements to 1
    tensor[:num_ones] = 1
    return tensor

# say we wanto to 

x = torch.tensor([[8, -1, 5, 3, 2, 1, 6, 7, 9, 100]]) 
y = torch.tensor([[1, 0, 0, 0, 0, 0, 0, 0, 1, 1]]) 

n, p = x.shape[1], proportion_of_ones(y)
hypercube_basis = get_hypercube_tensor(n,p)
print(hypercube_basis)


tensor([1., 1., 1., 0., 0., 0., 0., 0., 0., 0.])


# hard projection

In [25]:
torchsort.conv_proj.apply(x, hypercube_basis)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 1., 1.]])

## Soft projection

In [37]:
x = torch.tensor([[8, -1, 5, 3, 2, 1, 6, 7, 9, 100]]) 

torchsort.conv_proj.apply(x, hypercube_basis, 'l2', 3)

tensor([[0.6667, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.3333, 1.0000,
         1.0000]])